#define BARIERKA_GORA 0
#define BARIERKA_DOL 1
#define GRACZ_BEZ_BARIERKI 2
#define GRACZ_BARIERKA_GORA 3
#define GRACZ_BARIERKA_DOL 4
#define WROG_BEZ_BARIERKI 5
#define WROG_BARIERKA_GORA 6
#define WROG_BARIERKA_DOL 7

void ZaladujFonty();